Format example/test course JSON with Prettier
PrairieLearn/PrairieLearn pull request #10267
Opened 2024-07-19 21:02 UTC by nwalters512

Careful hand formatting of JSON will become less relevant as we move towards UI editors for JSON config files. This moves us in that direction by auto-formatting all JSON files in `testCourse` and `exampleCourse`.

I'm specifically requesting review from a lot of the core team to get a variety of viewpoints on this.

Note that this isn't perfect: currently, JSON files are generally formatted with `JSON.stringify(..., null, 2)` when PL writes them to disk. This means that editing one of these files with a PL GUI editor will result in formatting differences. IMO we should unconditionally use Prettier as a library to format JSON files when they're edited "automatically" by PL (as opposed to in the Ace file editor).

2024-07-19 21:13 UTC, eliotwrobson requested changes
A cursory look so far, but overall the auto formatting itself seems good. The only significant thing missing is my opinion is updating the vs code config to run prettier on file save.

2024-07-19 21:27 UTC, nwalters512 commented
@eliotwrobson are you looking for something more than this?

https://github.com/PrairieLearn/PrairieLearn/blob/18777ae2cf77a412fe7c46cdd107c93a65c5cc8c/.vscode/settings.json#L28-L31

2024-07-19 21:41 UTC, eliotwrobson commented
@nwalters512 oh whoops, I forgot we did that already 👍

2024-07-19 22:10 UTC, eliotwrobson approved these changes

2024-07-21 17:40 UTC, mwest1066 approved these changes
The reformatted files look great to me, I'm 100% on board with this direction.

2024-07-22 17:02 UTC, merged